#!/bin/bash
old=130.229.129.188
new=130.229.131.168
ufw delete allow from $old to any port 8888 proto tcp
ufw delete allow from $old to any port 8000 proto tcp
ufw allow from $new to any port 8888 proto tcp
ufw allow from $new to any port 8000 proto tcp
